config/routes.rb
Rails.application.routes.draw do
  root 'top#home'
  get 'canvazs/new', to: 'canvazs#new'
  get 'users/upload', to: 'users#upload'
  get 'users/follow', to: 'users#follow'
  get 'users/unfollow', to: 'users#unfollow'
  get 'users/folfow', to: 'users#folfow'
  get 'pages/dfsearch', to: 'pages#dfsearch'
  get 'pages/susearch', to: 'pages#susearch'
  get 'pages/folsearch', to: 'pages#folsearch'
  get 'images/supic', to: 'images#supic'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  resources:users
  resources:pages
  resources:images
  resources:uploads
  resources :canvazs, only: [:create]
  

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def home
  	@user = User.find_by(name: session[:login_name])
  	@q = Dfpic.ransack(params[:q])
  end
  
  def login
    user = User.authenticate(params[:name], params[:password_digest])
		if user
			session[:login_name] = params[:name]
			redirect_to root_path
		else
			#flash[:alert] = '現在ログインしていません'
			render 'top/login'
		end
  end
  
  def logout
		session.delete(:login_name)
		redirect_to root_path
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/home.html.erb
<div align="center"><h1>PictShare</h1></div>
<hr>
<div class="row">
<% if session[:login_name] != nil %>
<div class="col-md-4" align="center">
  <%= link_to 'ログアウト', top_logout_path, class:"btn btn-secondary" %></div>
  <div class="col-md-4" align="center">
  <%= link_to 'マイページ', user_path(@user), class:"btn btn-info" %></div>
  <div class="col-md-4" align="center">
  <%= link_to '絵を描く', canvazs_new_path , class:"btn btn-success"%></div>
 <% else %>
  <div class="coc-md-12"><%= link_to 'ログイン', top_login_path, class:"btn btn-primary" %></div>
<% end %>
</div>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div align="center">
<%= search_form_for(@q, :url => {:controller => :pages, :action => :index}) do |f| %>
  <%= f.label :title_or_title_cont, "画像を検索" %>
  <%= f.search_field :title_or_title_cont %>
  <br/>
  <%= f.submit %>
<% end %>
</div>

app/views/top/login.html.erb
<%= form_for 'top/login' do %>
<table>
  <tr>
    <td><%= label_tag :name, 'name' %></td>
    <td><%= text_field_tag :name %></td>
  </tr>
  <tr>
    <td><%= label_tag :password_digest, 'password' %></td>
    <td><%= password_field_tag :password_digest %></td>
  </tr>
  <tr>
    <td><%= submit_tag 'ログイン', class:"btn btn-outline-primary" %></td>
  </tr>
</table>
<% end %>
<br/>

<%= link_to '登録ページ' , new_user_path, class:"btn btn-outline-success" %><br>
<br>
<%= link_to 'トップへ', '/' %>