config/routes.rb
Rails.application.routes.draw do
  root 'top#home'
  get 'canvazs/new', to: 'canvazs#new'
  get 'users/upload', to: 'users#upload'
  get 'users/follow', to: 'users#follow'
  get 'users/unfollow', to: 'users#unfollow'
  get 'users/folfow', to: 'users#folfow'
  get 'pages/dfsearch', to: 'pages#dfsearch'
  get 'pages/susearch', to: 'pages#susearch'
  get 'pages/folsearch', to: 'pages#folsearch'
  get 'images/supic', to: 'images#supic'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  resources:users
  resources:pages
  resources:images
  resources:uploads
  resources :canvazs, only: [:create]
  

end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :userimage, ImagesUploader
    
    has_many :goodjobs, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :dfpics, dependent: :destroy
    has_many :gj_dfpics, source: :dfpic, through: :goodjobs, dependent: :destroy
    has_many :supics, dependent: :destroy
    has_many :gj_supics, source: :supic, through: :goodjobs, dependent: :destroy
    
    ########################################################################
    # フォロー機能関連付け                                                 #
    ########################################################################
    # 能動的関係の関連付け                                                 #
    has_many :active_relationships, class_name:  "Relationship",           # 
                                    foreign_key: "follower_id",            #
                                    dependent: :destroy                    #
    # followingの関連付け                                                  #
    has_many :following, through: :active_relationships, source: :followed #
    ########################################################################
    
    ########################################################################
    # フォロワー機能関連付け                                               #
    ########################################################################
    # 受動的関係の関連付け                                                 #
    has_many :passive_relationships, class_name:  "Relationship",          #
                                   foreign_key: "followed_id",             #
                                   dependent:   :destroy                   #
    # followedの関連付け                                                   #
    has_many :followers, through: :passive_relationships, source: :follower#
    ########################################################################
    
    ########################################################################
    # 関連付け用呼び出しメソッド                                           #
    ########################################################################
    # フォローする                                                         #
    def follow(other_user)                                                 #
      active_relationships.create(followed_id: other_user.id)              #
    end                                                                    #
                                                                           #
    #アンフォローする                                                      #
    def unfollow(other_user)                                               #
      active_relationships.find_by(followed_id: other_user.id).destroy     #
    end                                                                    #
                                                                           #
    #フォロー判定                                                          #
    def following?(other_user)                                             #
      following.include?(other_user)                                       #
    end                                                                    #
    ########################################################################
    
    validates :name , uniqueness: true
    
    def self.authenticate(name,password_digest)
          user = User.find_by(name: name)
        if user && user.password_digest == password_digest
          user
        else
          nil
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    user = session[:login_name]
    @user = User.find_by(name: user)
    name = params[:user][:name]
    mail = params[:user][:mail]
    intro = params[:user][:intro]
    @user.update(name: name, mail: mail, intro: intro)
    @user.save
    ###carrierwaveエラー対策###
    userimage = params[:user][:userimage]
    if userimage != @user.userimage
      @user.update(userimage: userimage)
      @user.save
    else
      redirect_to user_path
    end
    redirect_to user_path
  end
    
  def new
      @user = User.new
  end
  def create
      @user = User.new(
          name: params[:user][:name],
          mail: params[:user][:mail],
          age: params[:user][:age],
          password_digest: params[:user][:password_digest]
          )
      if @user.save
          redirect_to top_login_path
      else
          render 'user/new'
      end
  end
  
  def show
    if session[:login_name]
      user = session[:login_name]
      @user = User.find_by(name: user)
      render 'profile'
    else
      redirect_to '/'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

    def follow
      you = User.find_by(name: session[:login_name])
      d = params[:id]
      oth_user = Dfpic.find(d).user
      you.follow(oth_user)
      redirect_to '/'
    end
    
    def unfollow
      you = User.find_by(name: session[:login_name])
      d = params[:id]
      oth_user = Dfpic.find(d).user
      you.unfollow(oth_user)
      redirect_to '/'
    end
    
    def folfow
      id = params[:id]
      fol = params[:fol]
      if fol == "follow"
        @user = User.find(id).following
      elsif fol == "follower"
        @user = User.find(id).followers
      else
        @user = nil
      end
      @fol = params[:fol]
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <%= form_for @user , url: {action: :update} do |u| %>
<p><%= u.label :name, 'お名前' %>
<%= u.text_field :name%></p><br>
<p><%= u.label :mail, 'メールアドレス' %>
<%= u.text_field :mail%></p><br>
<p><%= u.label :intro, '自己紹介' %>
<%= u.text_field :intro%></p><br>
   <hr>
   <% if @user.userimage != nil %>
     <h2>現在のプロフィール画像</h2><br>
     <%= image_tag @user.userimage.thumb %><br>
   <% else %>
     <h1>まだプロフィール画像は登録されていないようです</h1><br>
   <% end %>
   <p><%= u.label :userimage, '新規プロフィール画像' %><%= u.file_field :userimage %></p>
 <%= u.submit '再登録' %>
 <% end %>

app/views/users/folfow.html.erb
<% if @fol == "follow" %>
  <h1>フォロー一覧</h1>
<% elsif @fol == "follower" %>
  <h1>フォロワー一覧</h1>
<% else %>
  <h1>?????????????????</h1>
<% end %>
<hr>
<% @user.each do |u| %>
<div style="border: 4px solid #82636b; border-radius: 240px 15px 185px 15px / 15px 200px 15px 185px; margin: 2em 0; padding: 2em;">
<div align="center"><h3><%= link_to u.name, controller: "pages", action: "folsearch", id: u.id %></h3></div>
</div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<form>
  <table>
  <tr>
    <td><%= f.label :name, 'name' %></td>
    <td><%= f.text_field :name, :placeholder => "name" %></td>
  </tr>
  <tr>
    <td><%= f.label :mail, 'mail' %></td>
    <td><%= f.text_field :mail, :placeholder => "example@example.com" %></td>
  </tr>
  <tr>
    <td><%= f.label :age, 'age' %></td>
    <td><%= f.number_field :age, :placeholder => "23(example)" %></td>
  </tr>
  <tr>
    <td><%= f.label :password_digest, 'password' %></td>
    <td><%= f.password_field :password_digest, :placeholder => "password" %></td>
  </tr>
  <tr>
    <td><%= f.submit '登録', class:"btn btn-outline-primary" %></td>
  </tr>
  </table>
</form>
<% end %>
<br/>
<%= link_to 'homeへ', '/' %>

app/views/users/profile.html.erb
<h1>ユーザー名<%= ">>#{@user.name}" %></h1>
<hr>
<div align="center">
<%= image_tag @user.userimage %>
<hr>
<strong><%= link_to "プロフィールを編集する", edit_user_path(@user.id), method: :get %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "フォローしてる", controller: "users", action: "folfow", id: @user.id, fol: "follow" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "フォローされてる", controller: "users", action: "folfow", id: @user.id, fol: "follower" %></strong>
<hr>
<div style="padding: 10px; margin-bottom: 10px; border: 5px double #333333; border-radius: 10px;">
<h1><%= link_to "投稿したお絵かき", pages_dfsearch_path, q: "原案" %></h1>
</div>
<div style="padding: 10px; margin-bottom: 10px; border: 5px double #333333; border-radius: 10px;">
<h1><%= link_to "提案した画像", pages_susearch_path, q: "提案" %></h1>
</div>
</div>